export interface Element {
  number: number
  symbol: string
  name: string
  nameVi: string
  mass: string
  category: ElementCategory
  row: number
  col: number
  electronConfig?: string
  electronegativity?: number
  density?: string
  meltingPoint?: string
  boilingPoint?: string
  yearDiscovered?: string
}

export type ElementCategory =
  | 'alkali-metal'
  | 'alkaline-earth'
  | 'transition-metal'
  | 'post-transition'
  | 'metalloid'
  | 'nonmetal'
  | 'halogen'
  | 'noble-gas'
  | 'lanthanide'
  | 'actinide'

export const CATEGORY_LABELS: Record<ElementCategory, string> = {
  'alkali-metal': 'Kim loại kiềm',
  'alkaline-earth': 'Kim loại kiềm thổ',
  'transition-metal': 'Kim loại chuyển tiếp',
  'post-transition': 'Kim loại sau chuyển tiếp',
  metalloid: 'Á kim',
  nonmetal: 'Phi kim',
  halogen: 'Halogen',
  'noble-gas': 'Khí hiếm',
  lanthanide: 'Lanthanide',
  actinide: 'Actinide',
}

export const CATEGORY_COLORS: Record<ElementCategory, string> = {
  'alkali-metal': '#FF6B4A',
  'alkaline-earth': '#FFB830',
  'transition-metal': '#38BDF8',
  'post-transition': '#4ADE80',
  metalloid: '#A78BFA',
  nonmetal: '#F472B6',
  halogen: '#FB923C',
  'noble-gas': '#22D3EE',
  lanthanide: '#E879F9',
  actinide: '#F87171',
}

export const elements: Element[] = [
  // Period 1
  {
    number: 1,
    symbol: 'H',
    name: 'Hydrogen',
    nameVi: 'Hiđrô',
    mass: '1.008',
    category: 'nonmetal',
    row: 1,
    col: 1,
    electronConfig: '1s¹',
    electronegativity: 2.2,
    density: '0.00009 g/cm³',
    meltingPoint: '-259.2 °C',
    boilingPoint: '-252.9 °C',
    yearDiscovered: '1766',
  },
  {
    number: 2,
    symbol: 'He',
    name: 'Helium',
    nameVi: 'Heli',
    mass: '4.003',
    category: 'noble-gas',
    row: 1,
    col: 18,
    electronConfig: '1s²',
    density: '0.000179 g/cm³',
    meltingPoint: '-272.2 °C',
    boilingPoint: '-268.9 °C',
    yearDiscovered: '1868',
  },

  // Period 2
  {
    number: 3,
    symbol: 'Li',
    name: 'Lithium',
    nameVi: 'Liti',
    mass: '6.941',
    category: 'alkali-metal',
    row: 2,
    col: 1,
    electronConfig: '[He] 2s¹',
    electronegativity: 0.98,
    density: '0.534 g/cm³',
    meltingPoint: '180.5 °C',
    boilingPoint: '1342 °C',
    yearDiscovered: '1817',
  },
  {
    number: 4,
    symbol: 'Be',
    name: 'Beryllium',
    nameVi: 'Berili',
    mass: '9.012',
    category: 'alkaline-earth',
    row: 2,
    col: 2,
    electronConfig: '[He] 2s²',
    electronegativity: 1.57,
    density: '1.85 g/cm³',
    meltingPoint: '1287 °C',
    boilingPoint: '2469 °C',
    yearDiscovered: '1798',
  },
  {
    number: 5,
    symbol: 'B',
    name: 'Boron',
    nameVi: 'Bo',
    mass: '10.81',
    category: 'metalloid',
    row: 2,
    col: 13,
    electronConfig: '[He] 2s² 2p¹',
    electronegativity: 2.04,
    density: '2.34 g/cm³',
    meltingPoint: '2076 °C',
    boilingPoint: '3927 °C',
    yearDiscovered: '1808',
  },
  {
    number: 6,
    symbol: 'C',
    name: 'Carbon',
    nameVi: 'Cacbon',
    mass: '12.01',
    category: 'nonmetal',
    row: 2,
    col: 14,
    electronConfig: '[He] 2s² 2p²',
    electronegativity: 2.55,
    density: '2.27 g/cm³',
    meltingPoint: '3550 °C',
    boilingPoint: '4027 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 7,
    symbol: 'N',
    name: 'Nitrogen',
    nameVi: 'Nitơ',
    mass: '14.01',
    category: 'nonmetal',
    row: 2,
    col: 15,
    electronConfig: '[He] 2s² 2p³',
    electronegativity: 3.04,
    density: '0.00125 g/cm³',
    meltingPoint: '-210 °C',
    boilingPoint: '-195.8 °C',
    yearDiscovered: '1772',
  },
  {
    number: 8,
    symbol: 'O',
    name: 'Oxygen',
    nameVi: 'Ôxy',
    mass: '16.00',
    category: 'nonmetal',
    row: 2,
    col: 16,
    electronConfig: '[He] 2s² 2p⁴',
    electronegativity: 3.44,
    density: '0.00143 g/cm³',
    meltingPoint: '-218.8 °C',
    boilingPoint: '-183 °C',
    yearDiscovered: '1774',
  },
  {
    number: 9,
    symbol: 'F',
    name: 'Fluorine',
    nameVi: 'Flo',
    mass: '19.00',
    category: 'halogen',
    row: 2,
    col: 17,
    electronConfig: '[He] 2s² 2p⁵',
    electronegativity: 3.98,
    density: '0.0017 g/cm³',
    meltingPoint: '-219.6 °C',
    boilingPoint: '-188.1 °C',
    yearDiscovered: '1886',
  },
  {
    number: 10,
    symbol: 'Ne',
    name: 'Neon',
    nameVi: 'Neon',
    mass: '20.18',
    category: 'noble-gas',
    row: 2,
    col: 18,
    electronConfig: '[He] 2s² 2p⁶',
    density: '0.0009 g/cm³',
    meltingPoint: '-248.6 °C',
    boilingPoint: '-246.1 °C',
    yearDiscovered: '1898',
  },

  // Period 3
  {
    number: 11,
    symbol: 'Na',
    name: 'Sodium',
    nameVi: 'Natri',
    mass: '22.99',
    category: 'alkali-metal',
    row: 3,
    col: 1,
    electronConfig: '[Ne] 3s¹',
    electronegativity: 0.93,
    density: '0.97 g/cm³',
    meltingPoint: '97.8 °C',
    boilingPoint: '883 °C',
    yearDiscovered: '1807',
  },
  {
    number: 12,
    symbol: 'Mg',
    name: 'Magnesium',
    nameVi: 'Magiê',
    mass: '24.31',
    category: 'alkaline-earth',
    row: 3,
    col: 2,
    electronConfig: '[Ne] 3s²',
    electronegativity: 1.31,
    density: '1.74 g/cm³',
    meltingPoint: '650 °C',
    boilingPoint: '1091 °C',
    yearDiscovered: '1755',
  },
  {
    number: 13,
    symbol: 'Al',
    name: 'Aluminium',
    nameVi: 'Nhôm',
    mass: '26.98',
    category: 'post-transition',
    row: 3,
    col: 13,
    electronConfig: '[Ne] 3s² 3p¹',
    electronegativity: 1.61,
    density: '2.7 g/cm³',
    meltingPoint: '660.3 °C',
    boilingPoint: '2519 °C',
    yearDiscovered: '1825',
  },
  {
    number: 14,
    symbol: 'Si',
    name: 'Silicon',
    nameVi: 'Silic',
    mass: '28.09',
    category: 'metalloid',
    row: 3,
    col: 14,
    electronConfig: '[Ne] 3s² 3p²',
    electronegativity: 1.9,
    density: '2.33 g/cm³',
    meltingPoint: '1414 °C',
    boilingPoint: '3265 °C',
    yearDiscovered: '1824',
  },
  {
    number: 15,
    symbol: 'P',
    name: 'Phosphorus',
    nameVi: 'Phốtpho',
    mass: '30.97',
    category: 'nonmetal',
    row: 3,
    col: 15,
    electronConfig: '[Ne] 3s² 3p³',
    electronegativity: 2.19,
    density: '1.82 g/cm³',
    meltingPoint: '44.2 °C',
    boilingPoint: '280.5 °C',
    yearDiscovered: '1669',
  },
  {
    number: 16,
    symbol: 'S',
    name: 'Sulfur',
    nameVi: 'Lưu huỳnh',
    mass: '32.07',
    category: 'nonmetal',
    row: 3,
    col: 16,
    electronConfig: '[Ne] 3s² 3p⁴',
    electronegativity: 2.58,
    density: '2.07 g/cm³',
    meltingPoint: '115.2 °C',
    boilingPoint: '444.6 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 17,
    symbol: 'Cl',
    name: 'Chlorine',
    nameVi: 'Clo',
    mass: '35.45',
    category: 'halogen',
    row: 3,
    col: 17,
    electronConfig: '[Ne] 3s² 3p⁵',
    electronegativity: 3.16,
    density: '0.0032 g/cm³',
    meltingPoint: '-101.5 °C',
    boilingPoint: '-34 °C',
    yearDiscovered: '1774',
  },
  {
    number: 18,
    symbol: 'Ar',
    name: 'Argon',
    nameVi: 'Argon',
    mass: '39.95',
    category: 'noble-gas',
    row: 3,
    col: 18,
    electronConfig: '[Ne] 3s² 3p⁶',
    density: '0.0018 g/cm³',
    meltingPoint: '-189.3 °C',
    boilingPoint: '-185.8 °C',
    yearDiscovered: '1894',
  },

  // Period 4
  {
    number: 19,
    symbol: 'K',
    name: 'Potassium',
    nameVi: 'Kali',
    mass: '39.10',
    category: 'alkali-metal',
    row: 4,
    col: 1,
    electronConfig: '[Ar] 4s¹',
    electronegativity: 0.82,
    density: '0.86 g/cm³',
    meltingPoint: '63.4 °C',
    boilingPoint: '759 °C',
    yearDiscovered: '1807',
  },
  {
    number: 20,
    symbol: 'Ca',
    name: 'Calcium',
    nameVi: 'Canxi',
    mass: '40.08',
    category: 'alkaline-earth',
    row: 4,
    col: 2,
    electronConfig: '[Ar] 4s²',
    electronegativity: 1.0,
    density: '1.55 g/cm³',
    meltingPoint: '842 °C',
    boilingPoint: '1484 °C',
    yearDiscovered: '1808',
  },
  {
    number: 21,
    symbol: 'Sc',
    name: 'Scandium',
    nameVi: 'Scandi',
    mass: '44.96',
    category: 'transition-metal',
    row: 4,
    col: 3,
    electronConfig: '[Ar] 3d¹ 4s²',
    electronegativity: 1.36,
    density: '2.99 g/cm³',
    meltingPoint: '1541 °C',
    boilingPoint: '2836 °C',
    yearDiscovered: '1879',
  },
  {
    number: 22,
    symbol: 'Ti',
    name: 'Titanium',
    nameVi: 'Titan',
    mass: '47.87',
    category: 'transition-metal',
    row: 4,
    col: 4,
    electronConfig: '[Ar] 3d² 4s²',
    electronegativity: 1.54,
    density: '4.54 g/cm³',
    meltingPoint: '1668 °C',
    boilingPoint: '3287 °C',
    yearDiscovered: '1791',
  },
  {
    number: 23,
    symbol: 'V',
    name: 'Vanadium',
    nameVi: 'Vanađi',
    mass: '50.94',
    category: 'transition-metal',
    row: 4,
    col: 5,
    electronConfig: '[Ar] 3d³ 4s²',
    electronegativity: 1.63,
    density: '6.11 g/cm³',
    meltingPoint: '1910 °C',
    boilingPoint: '3407 °C',
    yearDiscovered: '1801',
  },
  {
    number: 24,
    symbol: 'Cr',
    name: 'Chromium',
    nameVi: 'Crôm',
    mass: '52.00',
    category: 'transition-metal',
    row: 4,
    col: 6,
    electronConfig: '[Ar] 3d⁵ 4s¹',
    electronegativity: 1.66,
    density: '7.15 g/cm³',
    meltingPoint: '1907 °C',
    boilingPoint: '2671 °C',
    yearDiscovered: '1797',
  },
  {
    number: 25,
    symbol: 'Mn',
    name: 'Manganese',
    nameVi: 'Mangan',
    mass: '54.94',
    category: 'transition-metal',
    row: 4,
    col: 7,
    electronConfig: '[Ar] 3d⁵ 4s²',
    electronegativity: 1.55,
    density: '7.44 g/cm³',
    meltingPoint: '1246 °C',
    boilingPoint: '2061 °C',
    yearDiscovered: '1774',
  },
  {
    number: 26,
    symbol: 'Fe',
    name: 'Iron',
    nameVi: 'Sắt',
    mass: '55.85',
    category: 'transition-metal',
    row: 4,
    col: 8,
    electronConfig: '[Ar] 3d⁶ 4s²',
    electronegativity: 1.83,
    density: '7.87 g/cm³',
    meltingPoint: '1538 °C',
    boilingPoint: '2862 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 27,
    symbol: 'Co',
    name: 'Cobalt',
    nameVi: 'Coban',
    mass: '58.93',
    category: 'transition-metal',
    row: 4,
    col: 9,
    electronConfig: '[Ar] 3d⁷ 4s²',
    electronegativity: 1.88,
    density: '8.9 g/cm³',
    meltingPoint: '1495 °C',
    boilingPoint: '2927 °C',
    yearDiscovered: '1735',
  },
  {
    number: 28,
    symbol: 'Ni',
    name: 'Nickel',
    nameVi: 'Niken',
    mass: '58.69',
    category: 'transition-metal',
    row: 4,
    col: 10,
    electronConfig: '[Ar] 3d⁸ 4s²',
    electronegativity: 1.91,
    density: '8.91 g/cm³',
    meltingPoint: '1455 °C',
    boilingPoint: '2913 °C',
    yearDiscovered: '1751',
  },
  {
    number: 29,
    symbol: 'Cu',
    name: 'Copper',
    nameVi: 'Đồng',
    mass: '63.55',
    category: 'transition-metal',
    row: 4,
    col: 11,
    electronConfig: '[Ar] 3d¹⁰ 4s¹',
    electronegativity: 1.9,
    density: '8.96 g/cm³',
    meltingPoint: '1085 °C',
    boilingPoint: '2562 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 30,
    symbol: 'Zn',
    name: 'Zinc',
    nameVi: 'Kẽm',
    mass: '65.38',
    category: 'transition-metal',
    row: 4,
    col: 12,
    electronConfig: '[Ar] 3d¹⁰ 4s²',
    electronegativity: 1.65,
    density: '7.13 g/cm³',
    meltingPoint: '419.5 °C',
    boilingPoint: '907 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 31,
    symbol: 'Ga',
    name: 'Gallium',
    nameVi: 'Gali',
    mass: '69.72',
    category: 'post-transition',
    row: 4,
    col: 13,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹',
    electronegativity: 1.81,
    density: '5.91 g/cm³',
    meltingPoint: '29.8 °C',
    boilingPoint: '2204 °C',
    yearDiscovered: '1875',
  },
  {
    number: 32,
    symbol: 'Ge',
    name: 'Germanium',
    nameVi: 'Gecmani',
    mass: '72.63',
    category: 'metalloid',
    row: 4,
    col: 14,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p²',
    electronegativity: 2.01,
    density: '5.32 g/cm³',
    meltingPoint: '938.3 °C',
    boilingPoint: '2833 °C',
    yearDiscovered: '1886',
  },
  {
    number: 33,
    symbol: 'As',
    name: 'Arsenic',
    nameVi: 'Asen',
    mass: '74.92',
    category: 'metalloid',
    row: 4,
    col: 15,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p³',
    electronegativity: 2.18,
    density: '5.73 g/cm³',
    meltingPoint: '817 °C',
    boilingPoint: '614 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 34,
    symbol: 'Se',
    name: 'Selenium',
    nameVi: 'Selen',
    mass: '78.97',
    category: 'nonmetal',
    row: 4,
    col: 16,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴',
    electronegativity: 2.55,
    density: '4.81 g/cm³',
    meltingPoint: '221 °C',
    boilingPoint: '685 °C',
    yearDiscovered: '1817',
  },
  {
    number: 35,
    symbol: 'Br',
    name: 'Bromine',
    nameVi: 'Brôm',
    mass: '79.90',
    category: 'halogen',
    row: 4,
    col: 17,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',
    electronegativity: 2.96,
    density: '3.12 g/cm³',
    meltingPoint: '-7.2 °C',
    boilingPoint: '58.8 °C',
    yearDiscovered: '1826',
  },
  {
    number: 36,
    symbol: 'Kr',
    name: 'Krypton',
    nameVi: 'Krypton',
    mass: '83.80',
    category: 'noble-gas',
    row: 4,
    col: 18,
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶',
    density: '0.0037 g/cm³',
    meltingPoint: '-157.4 °C',
    boilingPoint: '-153.2 °C',
    yearDiscovered: '1898',
  },

  // Period 5
  {
    number: 37,
    symbol: 'Rb',
    name: 'Rubidium',
    nameVi: 'Rubiđi',
    mass: '85.47',
    category: 'alkali-metal',
    row: 5,
    col: 1,
    electronConfig: '[Kr] 5s¹',
    electronegativity: 0.82,
    density: '1.53 g/cm³',
    meltingPoint: '39.3 °C',
    boilingPoint: '688 °C',
    yearDiscovered: '1861',
  },
  {
    number: 38,
    symbol: 'Sr',
    name: 'Strontium',
    nameVi: 'Stronti',
    mass: '87.62',
    category: 'alkaline-earth',
    row: 5,
    col: 2,
    electronConfig: '[Kr] 5s²',
    electronegativity: 0.95,
    density: '2.64 g/cm³',
    meltingPoint: '777 °C',
    boilingPoint: '1382 °C',
    yearDiscovered: '1790',
  },
  {
    number: 39,
    symbol: 'Y',
    name: 'Yttrium',
    nameVi: 'Ytri',
    mass: '88.91',
    category: 'transition-metal',
    row: 5,
    col: 3,
    electronConfig: '[Kr] 4d¹ 5s²',
    electronegativity: 1.22,
    density: '4.47 g/cm³',
    meltingPoint: '1526 °C',
    boilingPoint: '3345 °C',
    yearDiscovered: '1794',
  },
  {
    number: 40,
    symbol: 'Zr',
    name: 'Zirconium',
    nameVi: 'Ziriconi',
    mass: '91.22',
    category: 'transition-metal',
    row: 5,
    col: 4,
    electronConfig: '[Kr] 4d² 5s²',
    electronegativity: 1.33,
    density: '6.51 g/cm³',
    meltingPoint: '1855 °C',
    boilingPoint: '4409 °C',
    yearDiscovered: '1789',
  },
  {
    number: 41,
    symbol: 'Nb',
    name: 'Niobium',
    nameVi: 'Niobi',
    mass: '92.91',
    category: 'transition-metal',
    row: 5,
    col: 5,
    electronConfig: '[Kr] 4d⁴ 5s¹',
    electronegativity: 1.6,
    density: '8.57 g/cm³',
    meltingPoint: '2477 °C',
    boilingPoint: '4744 °C',
    yearDiscovered: '1801',
  },
  {
    number: 42,
    symbol: 'Mo',
    name: 'Molybdenum',
    nameVi: 'Molypđen',
    mass: '95.95',
    category: 'transition-metal',
    row: 5,
    col: 6,
    electronConfig: '[Kr] 4d⁵ 5s¹',
    electronegativity: 2.16,
    density: '10.22 g/cm³',
    meltingPoint: '2623 °C',
    boilingPoint: '4639 °C',
    yearDiscovered: '1781',
  },
  {
    number: 43,
    symbol: 'Tc',
    name: 'Technetium',
    nameVi: 'Tecneti',
    mass: '(98)',
    category: 'transition-metal',
    row: 5,
    col: 7,
    electronConfig: '[Kr] 4d⁵ 5s²',
    electronegativity: 1.9,
    density: '11.5 g/cm³',
    meltingPoint: '2157 °C',
    boilingPoint: '4265 °C',
    yearDiscovered: '1937',
  },
  {
    number: 44,
    symbol: 'Ru',
    name: 'Ruthenium',
    nameVi: 'Ruteni',
    mass: '101.1',
    category: 'transition-metal',
    row: 5,
    col: 8,
    electronConfig: '[Kr] 4d⁷ 5s¹',
    electronegativity: 2.2,
    density: '12.37 g/cm³',
    meltingPoint: '2334 °C',
    boilingPoint: '4150 °C',
    yearDiscovered: '1844',
  },
  {
    number: 45,
    symbol: 'Rh',
    name: 'Rhodium',
    nameVi: 'Rođi',
    mass: '102.9',
    category: 'transition-metal',
    row: 5,
    col: 9,
    electronConfig: '[Kr] 4d⁸ 5s¹',
    electronegativity: 2.28,
    density: '12.41 g/cm³',
    meltingPoint: '1964 °C',
    boilingPoint: '3695 °C',
    yearDiscovered: '1803',
  },
  {
    number: 46,
    symbol: 'Pd',
    name: 'Palladium',
    nameVi: 'Palađi',
    mass: '106.4',
    category: 'transition-metal',
    row: 5,
    col: 10,
    electronConfig: '[Kr] 4d¹⁰',
    electronegativity: 2.2,
    density: '12.02 g/cm³',
    meltingPoint: '1555 °C',
    boilingPoint: '2963 °C',
    yearDiscovered: '1803',
  },
  {
    number: 47,
    symbol: 'Ag',
    name: 'Silver',
    nameVi: 'Bạc',
    mass: '107.9',
    category: 'transition-metal',
    row: 5,
    col: 11,
    electronConfig: '[Kr] 4d¹⁰ 5s¹',
    electronegativity: 1.93,
    density: '10.5 g/cm³',
    meltingPoint: '961.8 °C',
    boilingPoint: '2162 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 48,
    symbol: 'Cd',
    name: 'Cadmium',
    nameVi: 'Cađimi',
    mass: '112.4',
    category: 'transition-metal',
    row: 5,
    col: 12,
    electronConfig: '[Kr] 4d¹⁰ 5s²',
    electronegativity: 1.69,
    density: '8.65 g/cm³',
    meltingPoint: '321.1 °C',
    boilingPoint: '767 °C',
    yearDiscovered: '1817',
  },
  {
    number: 49,
    symbol: 'In',
    name: 'Indium',
    nameVi: 'Inđi',
    mass: '114.8',
    category: 'post-transition',
    row: 5,
    col: 13,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹',
    electronegativity: 1.78,
    density: '7.31 g/cm³',
    meltingPoint: '156.6 °C',
    boilingPoint: '2072 °C',
    yearDiscovered: '1863',
  },
  {
    number: 50,
    symbol: 'Sn',
    name: 'Tin',
    nameVi: 'Thiếc',
    mass: '118.7',
    category: 'post-transition',
    row: 5,
    col: 14,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p²',
    electronegativity: 1.96,
    density: '7.29 g/cm³',
    meltingPoint: '232 °C',
    boilingPoint: '2602 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 51,
    symbol: 'Sb',
    name: 'Antimony',
    nameVi: 'Antimon',
    mass: '121.8',
    category: 'metalloid',
    row: 5,
    col: 15,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p³',
    electronegativity: 2.05,
    density: '6.69 g/cm³',
    meltingPoint: '630.6 °C',
    boilingPoint: '1587 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 52,
    symbol: 'Te',
    name: 'Tellurium',
    nameVi: 'Telu',
    mass: '127.6',
    category: 'metalloid',
    row: 5,
    col: 16,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴',
    electronegativity: 2.1,
    density: '6.24 g/cm³',
    meltingPoint: '449.5 °C',
    boilingPoint: '988 °C',
    yearDiscovered: '1783',
  },
  {
    number: 53,
    symbol: 'I',
    name: 'Iodine',
    nameVi: 'Iốt',
    mass: '126.9',
    category: 'halogen',
    row: 5,
    col: 17,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',
    electronegativity: 2.66,
    density: '4.93 g/cm³',
    meltingPoint: '113.7 °C',
    boilingPoint: '184.3 °C',
    yearDiscovered: '1811',
  },
  {
    number: 54,
    symbol: 'Xe',
    name: 'Xenon',
    nameVi: 'Xenon',
    mass: '131.3',
    category: 'noble-gas',
    row: 5,
    col: 18,
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶',
    density: '0.0059 g/cm³',
    meltingPoint: '-111.8 °C',
    boilingPoint: '-108 °C',
    yearDiscovered: '1898',
  },

  // Period 6
  {
    number: 55,
    symbol: 'Cs',
    name: 'Caesium',
    nameVi: 'Xesi',
    mass: '132.9',
    category: 'alkali-metal',
    row: 6,
    col: 1,
    electronConfig: '[Xe] 6s¹',
    electronegativity: 0.79,
    density: '1.87 g/cm³',
    meltingPoint: '28.4 °C',
    boilingPoint: '671 °C',
    yearDiscovered: '1860',
  },
  {
    number: 56,
    symbol: 'Ba',
    name: 'Barium',
    nameVi: 'Bari',
    mass: '137.3',
    category: 'alkaline-earth',
    row: 6,
    col: 2,
    electronConfig: '[Xe] 6s²',
    electronegativity: 0.89,
    density: '3.59 g/cm³',
    meltingPoint: '727 °C',
    boilingPoint: '1897 °C',
    yearDiscovered: '1808',
  },
  // Lanthanides (row 9, cols 3-17 for display)
  {
    number: 57,
    symbol: 'La',
    name: 'Lanthanum',
    nameVi: 'Lantan',
    mass: '138.9',
    category: 'lanthanide',
    row: 9,
    col: 3,
    electronConfig: '[Xe] 5d¹ 6s²',
    electronegativity: 1.1,
    density: '6.15 g/cm³',
    meltingPoint: '920 °C',
    boilingPoint: '3464 °C',
    yearDiscovered: '1839',
  },
  {
    number: 58,
    symbol: 'Ce',
    name: 'Cerium',
    nameVi: 'Xeri',
    mass: '140.1',
    category: 'lanthanide',
    row: 9,
    col: 4,
    electronConfig: '[Xe] 4f¹ 5d¹ 6s²',
    electronegativity: 1.12,
    density: '6.77 g/cm³',
    meltingPoint: '798 °C',
    boilingPoint: '3443 °C',
    yearDiscovered: '1803',
  },
  {
    number: 59,
    symbol: 'Pr',
    name: 'Praseodymium',
    nameVi: 'Praseođim',
    mass: '140.9',
    category: 'lanthanide',
    row: 9,
    col: 5,
    electronConfig: '[Xe] 4f³ 6s²',
    electronegativity: 1.13,
    density: '6.77 g/cm³',
    meltingPoint: '931 °C',
    boilingPoint: '3520 °C',
    yearDiscovered: '1885',
  },
  {
    number: 60,
    symbol: 'Nd',
    name: 'Neodymium',
    nameVi: 'Neođim',
    mass: '144.2',
    category: 'lanthanide',
    row: 9,
    col: 6,
    electronConfig: '[Xe] 4f⁴ 6s²',
    electronegativity: 1.14,
    density: '7.01 g/cm³',
    meltingPoint: '1021 °C',
    boilingPoint: '3074 °C',
    yearDiscovered: '1885',
  },
  {
    number: 61,
    symbol: 'Pm',
    name: 'Promethium',
    nameVi: 'Prometi',
    mass: '(145)',
    category: 'lanthanide',
    row: 9,
    col: 7,
    electronConfig: '[Xe] 4f⁵ 6s²',
    electronegativity: 1.13,
    density: '7.26 g/cm³',
    meltingPoint: '1042 °C',
    boilingPoint: '3000 °C',
    yearDiscovered: '1945',
  },
  {
    number: 62,
    symbol: 'Sm',
    name: 'Samarium',
    nameVi: 'Samari',
    mass: '150.4',
    category: 'lanthanide',
    row: 9,
    col: 8,
    electronConfig: '[Xe] 4f⁶ 6s²',
    electronegativity: 1.17,
    density: '7.52 g/cm³',
    meltingPoint: '1074 °C',
    boilingPoint: '1794 °C',
    yearDiscovered: '1879',
  },
  {
    number: 63,
    symbol: 'Eu',
    name: 'Europium',
    nameVi: 'Europi',
    mass: '152.0',
    category: 'lanthanide',
    row: 9,
    col: 9,
    electronConfig: '[Xe] 4f⁷ 6s²',
    electronegativity: 1.2,
    density: '5.24 g/cm³',
    meltingPoint: '822 °C',
    boilingPoint: '1529 °C',
    yearDiscovered: '1901',
  },
  {
    number: 64,
    symbol: 'Gd',
    name: 'Gadolinium',
    nameVi: 'Gađolini',
    mass: '157.3',
    category: 'lanthanide',
    row: 9,
    col: 10,
    electronConfig: '[Xe] 4f⁷ 5d¹ 6s²',
    electronegativity: 1.2,
    density: '7.90 g/cm³',
    meltingPoint: '1313 °C',
    boilingPoint: '3273 °C',
    yearDiscovered: '1880',
  },
  {
    number: 65,
    symbol: 'Tb',
    name: 'Terbium',
    nameVi: 'Tecbi',
    mass: '158.9',
    category: 'lanthanide',
    row: 9,
    col: 11,
    electronConfig: '[Xe] 4f⁹ 6s²',
    electronegativity: 1.2,
    density: '8.23 g/cm³',
    meltingPoint: '1356 °C',
    boilingPoint: '3230 °C',
    yearDiscovered: '1843',
  },
  {
    number: 66,
    symbol: 'Dy',
    name: 'Dysprosium',
    nameVi: 'Đysprosi',
    mass: '162.5',
    category: 'lanthanide',
    row: 9,
    col: 12,
    electronConfig: '[Xe] 4f¹⁰ 6s²',
    electronegativity: 1.22,
    density: '8.55 g/cm³',
    meltingPoint: '1412 °C',
    boilingPoint: '2567 °C',
    yearDiscovered: '1886',
  },
  {
    number: 67,
    symbol: 'Ho',
    name: 'Holmium',
    nameVi: 'Honmi',
    mass: '164.9',
    category: 'lanthanide',
    row: 9,
    col: 13,
    electronConfig: '[Xe] 4f¹¹ 6s²',
    electronegativity: 1.23,
    density: '8.80 g/cm³',
    meltingPoint: '1474 °C',
    boilingPoint: '2700 °C',
    yearDiscovered: '1878',
  },
  {
    number: 68,
    symbol: 'Er',
    name: 'Erbium',
    nameVi: 'Ecbi',
    mass: '167.3',
    category: 'lanthanide',
    row: 9,
    col: 14,
    electronConfig: '[Xe] 4f¹² 6s²',
    electronegativity: 1.24,
    density: '9.07 g/cm³',
    meltingPoint: '1529 °C',
    boilingPoint: '2868 °C',
    yearDiscovered: '1843',
  },
  {
    number: 69,
    symbol: 'Tm',
    name: 'Thulium',
    nameVi: 'Tuli',
    mass: '168.9',
    category: 'lanthanide',
    row: 9,
    col: 15,
    electronConfig: '[Xe] 4f¹³ 6s²',
    electronegativity: 1.25,
    density: '9.32 g/cm³',
    meltingPoint: '1545 °C',
    boilingPoint: '1950 °C',
    yearDiscovered: '1879',
  },
  {
    number: 70,
    symbol: 'Yb',
    name: 'Ytterbium',
    nameVi: 'Ytecbi',
    mass: '173.0',
    category: 'lanthanide',
    row: 9,
    col: 16,
    electronConfig: '[Xe] 4f¹⁴ 6s²',
    electronegativity: 1.1,
    density: '6.90 g/cm³',
    meltingPoint: '819 °C',
    boilingPoint: '1196 °C',
    yearDiscovered: '1878',
  },
  {
    number: 71,
    symbol: 'Lu',
    name: 'Lutetium',
    nameVi: 'Luteti',
    mass: '175.0',
    category: 'lanthanide',
    row: 9,
    col: 17,
    electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²',
    electronegativity: 1.27,
    density: '9.84 g/cm³',
    meltingPoint: '1663 °C',
    boilingPoint: '3402 °C',
    yearDiscovered: '1907',
  },
  // Back to period 6
  {
    number: 72,
    symbol: 'Hf',
    name: 'Hafnium',
    nameVi: 'Hafni',
    mass: '178.5',
    category: 'transition-metal',
    row: 6,
    col: 4,
    electronConfig: '[Xe] 4f¹⁴ 5d² 6s²',
    electronegativity: 1.3,
    density: '13.31 g/cm³',
    meltingPoint: '2233 °C',
    boilingPoint: '4603 °C',
    yearDiscovered: '1923',
  },
  {
    number: 73,
    symbol: 'Ta',
    name: 'Tantalum',
    nameVi: 'Tantan',
    mass: '180.9',
    category: 'transition-metal',
    row: 6,
    col: 5,
    electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²',
    electronegativity: 1.5,
    density: '16.65 g/cm³',
    meltingPoint: '3017 °C',
    boilingPoint: '5458 °C',
    yearDiscovered: '1802',
  },
  {
    number: 74,
    symbol: 'W',
    name: 'Tungsten',
    nameVi: 'Vonfram',
    mass: '183.8',
    category: 'transition-metal',
    row: 6,
    col: 6,
    electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    electronegativity: 2.36,
    density: '19.25 g/cm³',
    meltingPoint: '3422 °C',
    boilingPoint: '5555 °C',
    yearDiscovered: '1783',
  },
  {
    number: 75,
    symbol: 'Re',
    name: 'Rhenium',
    nameVi: 'Reni',
    mass: '186.2',
    category: 'transition-metal',
    row: 6,
    col: 7,
    electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    electronegativity: 1.9,
    density: '21.02 g/cm³',
    meltingPoint: '3186 °C',
    boilingPoint: '5596 °C',
    yearDiscovered: '1925',
  },
  {
    number: 76,
    symbol: 'Os',
    name: 'Osmium',
    nameVi: 'Osimi',
    mass: '190.2',
    category: 'transition-metal',
    row: 6,
    col: 8,
    electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    electronegativity: 2.2,
    density: '22.59 g/cm³',
    meltingPoint: '3033 °C',
    boilingPoint: '5012 °C',
    yearDiscovered: '1803',
  },
  {
    number: 77,
    symbol: 'Ir',
    name: 'Iridium',
    nameVi: 'Iriđi',
    mass: '192.2',
    category: 'transition-metal',
    row: 6,
    col: 9,
    electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    electronegativity: 2.2,
    density: '22.56 g/cm³',
    meltingPoint: '2446 °C',
    boilingPoint: '4428 °C',
    yearDiscovered: '1803',
  },
  {
    number: 78,
    symbol: 'Pt',
    name: 'Platinum',
    nameVi: 'Platin',
    mass: '195.1',
    category: 'transition-metal',
    row: 6,
    col: 10,
    electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    electronegativity: 2.28,
    density: '21.45 g/cm³',
    meltingPoint: '1768 °C',
    boilingPoint: '3825 °C',
    yearDiscovered: '1735',
  },
  {
    number: 79,
    symbol: 'Au',
    name: 'Gold',
    nameVi: 'Vàng',
    mass: '197.0',
    category: 'transition-metal',
    row: 6,
    col: 11,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    electronegativity: 2.54,
    density: '19.32 g/cm³',
    meltingPoint: '1064 °C',
    boilingPoint: '2856 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 80,
    symbol: 'Hg',
    name: 'Mercury',
    nameVi: 'Thủy ngân',
    mass: '200.6',
    category: 'transition-metal',
    row: 6,
    col: 12,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    electronegativity: 2.0,
    density: '13.53 g/cm³',
    meltingPoint: '-38.8 °C',
    boilingPoint: '357 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 81,
    symbol: 'Tl',
    name: 'Thallium',
    nameVi: 'Tali',
    mass: '204.4',
    category: 'post-transition',
    row: 6,
    col: 13,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    electronegativity: 1.62,
    density: '11.85 g/cm³',
    meltingPoint: '304 °C',
    boilingPoint: '1473 °C',
    yearDiscovered: '1861',
  },
  {
    number: 82,
    symbol: 'Pb',
    name: 'Lead',
    nameVi: 'Chì',
    mass: '207.2',
    category: 'post-transition',
    row: 6,
    col: 14,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    electronegativity: 1.87,
    density: '11.34 g/cm³',
    meltingPoint: '327.5 °C',
    boilingPoint: '1749 °C',
    yearDiscovered: 'Cổ đại',
  },
  {
    number: 83,
    symbol: 'Bi',
    name: 'Bismuth',
    nameVi: 'Bitmut',
    mass: '209.0',
    category: 'post-transition',
    row: 6,
    col: 15,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    electronegativity: 2.02,
    density: '9.75 g/cm³',
    meltingPoint: '271.4 °C',
    boilingPoint: '1564 °C',
    yearDiscovered: '1753',
  },
  {
    number: 84,
    symbol: 'Po',
    name: 'Polonium',
    nameVi: 'Poloni',
    mass: '(209)',
    category: 'post-transition',
    row: 6,
    col: 16,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    electronegativity: 2.0,
    density: '9.20 g/cm³',
    meltingPoint: '254 °C',
    boilingPoint: '962 °C',
    yearDiscovered: '1898',
  },
  {
    number: 85,
    symbol: 'At',
    name: 'Astatine',
    nameVi: 'Astatin',
    mass: '(210)',
    category: 'halogen',
    row: 6,
    col: 17,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    electronegativity: 2.2,
    density: '~7 g/cm³',
    meltingPoint: '302 °C',
    boilingPoint: '337 °C',
    yearDiscovered: '1940',
  },
  {
    number: 86,
    symbol: 'Rn',
    name: 'Radon',
    nameVi: 'Rađon',
    mass: '(222)',
    category: 'noble-gas',
    row: 6,
    col: 18,
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    density: '0.0097 g/cm³',
    meltingPoint: '-71 °C',
    boilingPoint: '-61.7 °C',
    yearDiscovered: '1900',
  },

  // Period 7
  {
    number: 87,
    symbol: 'Fr',
    name: 'Francium',
    nameVi: 'Franxi',
    mass: '(223)',
    category: 'alkali-metal',
    row: 7,
    col: 1,
    electronConfig: '[Rn] 7s¹',
    electronegativity: 0.7,
    density: '~1.87 g/cm³',
    meltingPoint: '27 °C',
    boilingPoint: '677 °C',
    yearDiscovered: '1939',
  },
  {
    number: 88,
    symbol: 'Ra',
    name: 'Radium',
    nameVi: 'Rađi',
    mass: '(226)',
    category: 'alkaline-earth',
    row: 7,
    col: 2,
    electronConfig: '[Rn] 7s²',
    electronegativity: 0.9,
    density: '5.5 g/cm³',
    meltingPoint: '700 °C',
    boilingPoint: '1737 °C',
    yearDiscovered: '1898',
  },
  // Actinides (row 10, cols 3-17)
  {
    number: 89,
    symbol: 'Ac',
    name: 'Actinium',
    nameVi: 'Actini',
    mass: '(227)',
    category: 'actinide',
    row: 10,
    col: 3,
    electronConfig: '[Rn] 6d¹ 7s²',
    electronegativity: 1.1,
    density: '10.07 g/cm³',
    meltingPoint: '1050 °C',
    boilingPoint: '3198 °C',
    yearDiscovered: '1899',
  },
  {
    number: 90,
    symbol: 'Th',
    name: 'Thorium',
    nameVi: 'Thori',
    mass: '232.0',
    category: 'actinide',
    row: 10,
    col: 4,
    electronConfig: '[Rn] 6d² 7s²',
    electronegativity: 1.3,
    density: '11.72 g/cm³',
    meltingPoint: '1750 °C',
    boilingPoint: '4788 °C',
    yearDiscovered: '1829',
  },
  {
    number: 91,
    symbol: 'Pa',
    name: 'Protactinium',
    nameVi: 'Protactini',
    mass: '231.0',
    category: 'actinide',
    row: 10,
    col: 5,
    electronConfig: '[Rn] 5f² 6d¹ 7s²',
    electronegativity: 1.5,
    density: '15.37 g/cm³',
    meltingPoint: '1572 °C',
    boilingPoint: '4027 °C',
    yearDiscovered: '1913',
  },
  {
    number: 92,
    symbol: 'U',
    name: 'Uranium',
    nameVi: 'Urani',
    mass: '238.0',
    category: 'actinide',
    row: 10,
    col: 6,
    electronConfig: '[Rn] 5f³ 6d¹ 7s²',
    electronegativity: 1.38,
    density: '18.95 g/cm³',
    meltingPoint: '1135 °C',
    boilingPoint: '4131 °C',
    yearDiscovered: '1789',
  },
  {
    number: 93,
    symbol: 'Np',
    name: 'Neptunium',
    nameVi: 'Neptuni',
    mass: '(237)',
    category: 'actinide',
    row: 10,
    col: 7,
    electronConfig: '[Rn] 5f⁴ 6d¹ 7s²',
    electronegativity: 1.36,
    density: '20.45 g/cm³',
    meltingPoint: '644 °C',
    boilingPoint: '3902 °C',
    yearDiscovered: '1940',
  },
  {
    number: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    nameVi: 'Plutoni',
    mass: '(244)',
    category: 'actinide',
    row: 10,
    col: 8,
    electronConfig: '[Rn] 5f⁶ 7s²',
    electronegativity: 1.28,
    density: '19.84 g/cm³',
    meltingPoint: '640 °C',
    boilingPoint: '3228 °C',
    yearDiscovered: '1940',
  },
  {
    number: 95,
    symbol: 'Am',
    name: 'Americium',
    nameVi: 'Americi',
    mass: '(243)',
    category: 'actinide',
    row: 10,
    col: 9,
    electronConfig: '[Rn] 5f⁷ 7s²',
    electronegativity: 1.3,
    density: '13.69 g/cm³',
    meltingPoint: '1176 °C',
    boilingPoint: '2011 °C',
    yearDiscovered: '1944',
  },
  {
    number: 96,
    symbol: 'Cm',
    name: 'Curium',
    nameVi: 'Curi',
    mass: '(247)',
    category: 'actinide',
    row: 10,
    col: 10,
    electronConfig: '[Rn] 5f⁷ 6d¹ 7s²',
    electronegativity: 1.3,
    density: '13.51 g/cm³',
    meltingPoint: '1345 °C',
    boilingPoint: '3110 °C',
    yearDiscovered: '1944',
  },
  {
    number: 97,
    symbol: 'Bk',
    name: 'Berkelium',
    nameVi: 'Beckeli',
    mass: '(247)',
    category: 'actinide',
    row: 10,
    col: 11,
    electronConfig: '[Rn] 5f⁹ 7s²',
    electronegativity: 1.3,
    density: '14.79 g/cm³',
    meltingPoint: '1050 °C',
    yearDiscovered: '1949',
  },
  {
    number: 98,
    symbol: 'Cf',
    name: 'Californium',
    nameVi: 'Califoni',
    mass: '(251)',
    category: 'actinide',
    row: 10,
    col: 12,
    electronConfig: '[Rn] 5f¹⁰ 7s²',
    electronegativity: 1.3,
    density: '15.1 g/cm³',
    meltingPoint: '900 °C',
    yearDiscovered: '1950',
  },
  {
    number: 99,
    symbol: 'Es',
    name: 'Einsteinium',
    nameVi: 'Einsteini',
    mass: '(252)',
    category: 'actinide',
    row: 10,
    col: 13,
    electronConfig: '[Rn] 5f¹¹ 7s²',
    electronegativity: 1.3,
    density: '8.84 g/cm³',
    meltingPoint: '860 °C',
    yearDiscovered: '1952',
  },
  {
    number: 100,
    symbol: 'Fm',
    name: 'Fermium',
    nameVi: 'Fecmi',
    mass: '(257)',
    category: 'actinide',
    row: 10,
    col: 14,
    electronConfig: '[Rn] 5f¹² 7s²',
    electronegativity: 1.3,
    meltingPoint: '1527 °C',
    yearDiscovered: '1952',
  },
  {
    number: 101,
    symbol: 'Md',
    name: 'Mendelevium',
    nameVi: 'Menđelevi',
    mass: '(258)',
    category: 'actinide',
    row: 10,
    col: 15,
    electronConfig: '[Rn] 5f¹³ 7s²',
    electronegativity: 1.3,
    meltingPoint: '827 °C',
    yearDiscovered: '1955',
  },
  {
    number: 102,
    symbol: 'No',
    name: 'Nobelium',
    nameVi: 'Nobeli',
    mass: '(259)',
    category: 'actinide',
    row: 10,
    col: 16,
    electronConfig: '[Rn] 5f¹⁴ 7s²',
    electronegativity: 1.3,
    meltingPoint: '827 °C',
    yearDiscovered: '1958',
  },
  {
    number: 103,
    symbol: 'Lr',
    name: 'Lawrencium',
    nameVi: 'Lorenci',
    mass: '(266)',
    category: 'actinide',
    row: 10,
    col: 17,
    electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹',
    electronegativity: 1.3,
    yearDiscovered: '1961',
  },
  // Back to period 7
  {
    number: 104,
    symbol: 'Rf',
    name: 'Rutherfordium',
    nameVi: 'Rutheforđi',
    mass: '(267)',
    category: 'transition-metal',
    row: 7,
    col: 4,
    yearDiscovered: '1964',
  },
  {
    number: 105,
    symbol: 'Db',
    name: 'Dubnium',
    nameVi: 'Đubni',
    mass: '(268)',
    category: 'transition-metal',
    row: 7,
    col: 5,
    yearDiscovered: '1967',
  },
  {
    number: 106,
    symbol: 'Sg',
    name: 'Seaborgium',
    nameVi: 'Siabogi',
    mass: '(271)',
    category: 'transition-metal',
    row: 7,
    col: 6,
    yearDiscovered: '1974',
  },
  {
    number: 107,
    symbol: 'Bh',
    name: 'Bohrium',
    nameVi: 'Bohri',
    mass: '(270)',
    category: 'transition-metal',
    row: 7,
    col: 7,
    yearDiscovered: '1981',
  },
  {
    number: 108,
    symbol: 'Hs',
    name: 'Hassium',
    nameVi: 'Hassi',
    mass: '(277)',
    category: 'transition-metal',
    row: 7,
    col: 8,
    yearDiscovered: '1984',
  },
  {
    number: 109,
    symbol: 'Mt',
    name: 'Meitnerium',
    nameVi: 'Maitneri',
    mass: '(276)',
    category: 'transition-metal',
    row: 7,
    col: 9,
    yearDiscovered: '1982',
  },
  {
    number: 110,
    symbol: 'Ds',
    name: 'Darmstadtium',
    nameVi: 'Đamstati',
    mass: '(281)',
    category: 'transition-metal',
    row: 7,
    col: 10,
    yearDiscovered: '1994',
  },
  {
    number: 111,
    symbol: 'Rg',
    name: 'Roentgenium',
    nameVi: 'Rơngeni',
    mass: '(282)',
    category: 'transition-metal',
    row: 7,
    col: 11,
    yearDiscovered: '1994',
  },
  {
    number: 112,
    symbol: 'Cn',
    name: 'Copernicium',
    nameVi: 'Côpecnixi',
    mass: '(285)',
    category: 'transition-metal',
    row: 7,
    col: 12,
    yearDiscovered: '1996',
  },
  {
    number: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    nameVi: 'Nihoni',
    mass: '(286)',
    category: 'post-transition',
    row: 7,
    col: 13,
    yearDiscovered: '2003',
  },
  {
    number: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    nameVi: 'Flerovi',
    mass: '(289)',
    category: 'post-transition',
    row: 7,
    col: 14,
    yearDiscovered: '1998',
  },
  {
    number: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    nameVi: 'Moscovi',
    mass: '(290)',
    category: 'post-transition',
    row: 7,
    col: 15,
    yearDiscovered: '2003',
  },
  {
    number: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    nameVi: 'Livemori',
    mass: '(293)',
    category: 'post-transition',
    row: 7,
    col: 16,
    yearDiscovered: '2000',
  },
  {
    number: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    nameVi: 'Tennesin',
    mass: '(294)',
    category: 'halogen',
    row: 7,
    col: 17,
    yearDiscovered: '2010',
  },
  {
    number: 118,
    symbol: 'Og',
    name: 'Oganesson',
    nameVi: 'Oganeson',
    mass: '(294)',
    category: 'noble-gas',
    row: 7,
    col: 18,
    yearDiscovered: '2002',
  },
]
